In [ ]:
import pymongo
import mongodb.mongosetupvars as msv
import pandas as pd
import numpy as np

In [13]:
import certifi # <--- Add this import
import pymongo
import pandas as pd

# ... your credentials setup ...

uri = f"mongodb+srv://{msv.USERNAME}:{msv.PASSWORD}@{msv.HOST}"

# Pass the tlsCAFile parameter using certifi
ca = certifi.where()
client = pymongo.MongoClient(uri, tlsCAFile=ca) 

db = client[msv.DATABASE]
collection = db[msv.COLLECTION]


df = pd.read_csv('./data/general/news.csv')
df.head()

,news_id,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL

In [15]:
df = df.drop(columns=['index', 'title'])
df.head()

KeyError: "['index'] not found in axis"

InsertManyResult([ObjectId('699534f9ef866a3d38792139'), ObjectId('699534f9ef866a3d3879213a'), ObjectId('699534f9ef866a3d3879213b'), ObjectId('699534f9ef866a3d3879213c'), ObjectId('699534f9ef866a3d3879213d'), ObjectId('699534f9ef866a3d3879213e'), ObjectId('699534f9ef866a3d3879213f'), ObjectId('699534f9ef866a3d38792140'), ObjectId('699534f9ef866a3d38792141'), ObjectId('699534f9ef866a3d38792142'), ObjectId('699534f9ef866a3d38792143'), ObjectId('699534f9ef866a3d38792144'), ObjectId('699534f9ef866a3d38792145'), ObjectId('699534f9ef866a3d38792146'), ObjectId('699534f9ef866a3d38792147'), ObjectId('699534f9ef866a3d38792148'), ObjectId('699534f9ef866a3d38792149'), ObjectId('699534f9ef866a3d3879214a'), ObjectId('699534f9ef866a3d3879214b'), ObjectId('699534f9ef866a3d3879214c'), ObjectId('699534f9ef866a3d3879214d'), ObjectId('699534f9ef866a3d3879214e'), ObjectId('699534f9ef866a3d3879214f'), ObjectId('699534f9ef866a3d38792150'), ObjectId('699534f9ef866a3d38792151'), ObjectId('699534f9ef866a3d38792152'), ObjectId('699534f9ef866a3d38792153'), ObjectId('699534f9ef866a3d38792154'), ObjectId('699534f9ef866a3d38792155'), ObjectId('699534f9ef866a3d38792156'), ObjectId('699534f9ef866a3d38792157'), ObjectId('699534f9ef866a3d38792158'), ObjectId('699534f9ef866a3d38792159'), ObjectId('699534f9ef866a3d3879215a'), ObjectId('699534f9ef866a3d3879215b'), ObjectId('699534f9ef866a3d3879215c'), ObjectId('699534f9ef866a3d3879215d'), ObjectId('699534f9ef866a3d3879215e'), ObjectId('699534f9ef866a3d3879215f'), ObjectId('699534f9ef866a3d38792160'), ObjectId('699534f9ef866a3d38792161'), ObjectId('699534f9ef866a3d38792162'), ObjectId('699534f9ef866a3d38792163'), ObjectId('699534f9ef866a3d38792164'), ObjectId('699534f9ef866a3d38792165'), ObjectId('699534f9ef866a3d38792166'), ObjectId('699534f9ef866a3d38792167'), ObjectId('699534f9ef866a3d38792168'), ObjectId('699534f9ef866a3d38792169'), ObjectId('699534f9ef866a3d3879216a'), ObjectId('699534f9ef866a3d3879216b'), ObjectId('699534f9ef866a3d3879216c'), ObjectId('699534f9ef866a3d3879216d'), ObjectId('699534f9ef866a3d3879216e'), ObjectId('699534f9ef866a3d3879216f'), ObjectId('699534f9ef866a3d38792170'), ObjectId('699534f9ef866a3d38792171'), ObjectId('699534f9ef866a3d38792172'), ObjectId('699534f9ef866a3d38792173'), ObjectId('699534f9ef866a3d38792174'), ObjectId('699534f9ef866a3d38792175'), ObjectId('699534f9ef866a3d38792176'), ObjectId('699534f9ef866a3d38792177'), ObjectId('699534f9ef866a3d38792178'), ObjectId('699534f9ef866a3d38792179'), ObjectId('699534f9ef866a3d3879217a'), ObjectId('699534f9ef866a3d3879217b'), ObjectId('699534f9ef866a3d3879217c'), ObjectId('699534f9ef866a3d3879217d'), ObjectId('699534f9ef866a3d3879217e'), ObjectId('699534f9ef866a3d3879217f'), ObjectId('699534f9ef866a3d38792180'), ObjectId('699534f9ef866a3d38792181'), ObjectId('699534f9ef866a3d38792182'), ObjectId('699534f9ef866a3d38792183'), ObjectId('699534f9ef866a3d38792184'), ObjectId('699534f9ef866a3d38792185'), ObjectId('699534f9ef866a3d38792186'), ObjectId('699534f9ef866a3d38792187'), ObjectId('699534f9ef866a3d38792188'), ObjectId('699534f9ef866a3d38792189'), ObjectId('699534f9ef866a3d3879218a'), ObjectId('699534f9ef866a3d3879218b'), ObjectId('699534f9ef866a3d3879218c'), ObjectId('699534f9ef866a3d3879218d'), ObjectId('699534f9ef866a3d3879218e'), ObjectId('699534f9ef866a3d3879218f'), ObjectId('699534f9ef866a3d38792190'), ObjectId('699534f9ef866a3d38792191'), ObjectId('699534f9ef866a3d38792192'), ObjectId('699534f9ef866a3d38792193'), ObjectId('699534f9ef866a3d38792194'), ObjectId('699534f9ef866a3d38792195'), ObjectId('699534f9ef866a3d38792196'), ObjectId('699534f9ef866a3d38792197'), ObjectId('699534f9ef866a3d38792198'), ObjectId('699534f9ef866a3d38792199'), ObjectId('699534f9ef866a3d3879219a'), ObjectId('699534f9ef866a3d3879219b'), ObjectId('699534f9ef866a3d3879219c'), ObjectId('699534f9ef866a3d3879219d'), ObjectId('699534f9ef866a3d3879219e'), ObjectId('699534f9ef866a3d3879219f'), ObjectId('699534f9ef866a3d387921a0'), ObjectId('699534f9ef866a3d387921a1'), ObjectId('699534f9ef866a3d387921a2'), ObjectId('699534f9ef866a3d387921a3'), ObjectId('699534f9ef866a3d387921a4'), ObjectId('699534f9ef866a3d387921a5'), ObjectId('699534f9ef866a3d387921a6'), ObjectId('699534f9ef866a3d387921a7'), ObjectId('699534f9ef866a3d387921a8'), ObjectId('699534f9ef866a3d387921a9'), ObjectId('699534f9ef866a3d387921aa'), ObjectId('699534f9ef866a3d387921ab'), ObjectId('699534f9ef866a3d387921ac'), ObjectId('699534f9ef866a3d387921ad'), ObjectId('699534f9ef866a3d387921ae'), ObjectId('699534f9ef866a3d387921af'), ObjectId('699534f9ef866a3d387921b0'), ObjectId('699534f9ef866a3d387921b1'), ObjectId('699534f9ef866a3d387921b2'), ObjectId('699534f9ef866a3d387921b3'), ObjectId('699534f9ef866a3d387921b4'), ObjectId('699534f9ef866a3d387921b5'), ObjectId('699534f9ef866a3d387921b6'), ObjectId('699534f9ef866a3d387921b7'), ObjectId('699534f9ef866a3d387921b8'), ObjectId('699534f9ef866a3d387921b9'), ObjectId('699534f9ef866a3d387921ba'), ObjectId('699534f9ef866a3d387921bb'), ObjectId('699534f9ef866a3d387921bc'), ObjectId('699534f9ef866a3d387921bd'), ObjectId('699534f9ef866a3d387921be'), ObjectId('699534f9ef866a3d387921bf'), ObjectId('699534f9ef866a3d387921c0'), ObjectId('699534f9ef866a3d387921c1'), ObjectId('699534f9ef866a3d387921c2'), ObjectId('699534f9ef866a3d387921c3'), ObjectId('699534f9ef866a3d387921c4'), ObjectId('699534f9ef866a3d387921c5'), ObjectId('699534f9ef866a3d387921c6'), ObjectId('699534f9ef866a3d387921c7'), ObjectId('699534f9ef866a3d387921c8'), ObjectId('699534f9ef866a3d387921c9'), ObjectId('699534f9ef866a3d387921ca'), ObjectId('699534f9ef866a3d387921cb'), ObjectId('699534f9ef866a3d387921cc'), ObjectId('699534f9ef866a3d387921cd'), ObjectId('699534f9ef866a3d387921ce'), ObjectId('699534f9ef866a3d387921cf'), ObjectId('699534f9ef866a3d387921d0'), ObjectId('699534f9ef866a3d387921d1'), ObjectId('699534f9ef866a3d387921d2'), ObjectId('699534f9ef866a3d387921d3'), ObjectId('699534f9ef866a3d387921d4'), ObjectId('699534f9ef866a3d387921d5'), ObjectId('699534f9ef866a3d387921d6'), ObjectId('699534f9ef866a3d387921d7'), ObjectId('699534f9ef866a3d387921d8'), ObjectId('699534f9ef866a3d387921d9'), ObjectId('699534f9ef866a3d387921da'), ObjectId('699534f9ef866a3d387921db'), ObjectId('699534f9ef866a3d387921dc'), ObjectId('699534f9ef866a3d387921dd'), ObjectId('699534f9ef866a3d387921de'), ObjectId('699534f9ef866a3d387921df'), ObjectId('699534f9ef866a3d387921e0'), ObjectId('699534f9ef866a3d387921e1'), ObjectId('699534f9ef866a3d387921e2'), ObjectId('699534f9ef866a3d387921e3'), ObjectId('699534f9ef866a3d387921e4'), ObjectId('699534f9ef866a3d387921e5'), ObjectId('699534f9ef866a3d387921e6'), ObjectId('699534f9ef866a3d387921e7'), ObjectId('699534f9ef866a3d387921e8'), ObjectId('699534f9ef866a3d387921e9'), ObjectId('699534f9ef866a3d387921ea'), ObjectId('699534f9ef866a3d387921eb'), ObjectId('699534f9ef866a3d387921ec'), ObjectId('699534f9ef866a3d387921ed'), ObjectId('699534f9ef866a3d387921ee'), ObjectId('699534f9ef866a3d387921ef'), ObjectId('699534f9ef866a3d387921f0'), ObjectId('699534f9ef866a3d387921f1'), ObjectId('699534f9ef866a3d387921f2'), ObjectId('699534f9ef866a3d387921f3'), ObjectId('699534f9ef866a3d387921f4'), ObjectId('699534f9ef866a3d387921f5'), ObjectId('699534f9ef866a3d387921f6'), ObjectId('699534f9ef866a3d387921f7'), ObjectId('699534f9ef866a3d387921f8'), ObjectId('699534f9ef866a3d387921f9'), ObjectId('699534f9ef866a3d387921fa'), ObjectId('699534f9ef866a3d387921fb'), ObjectId('699534f9ef866a3d387921fc'), ObjectId('699534f9ef866a3d387921fd'), ObjectId('699534f9ef866a3d387921fe'), ObjectId('699534f9ef866a3d387921ff'), ObjectId('699534f9ef866a3d38792200'), ObjectId('699534f9ef866a3d38792201'), ObjectId('699534f9ef866a3d38792202'), ObjectId('699534f9ef866a3d38792203'), ObjectId('699534f9ef866a3d38792204'), ObjectId('699534f9ef866a3d38792205'), ObjectId('699534f9ef866a3d38792206'), ObjectId('699534f9ef866a3d38792207'), ObjectId('699534f9ef866a3d38792208'), ObjectId('699534f9ef866a3d38792209'), ObjectId('699534f9ef866a3d3879220a'), ObjectId('699534f9ef866a3d3879220b'), ObjectId('699534f9ef866a3d3879220c'), ObjectId('699534f9ef866a3d3879220d'), ObjectId('699534f9ef866a3d3879220e'), ObjectId('699534f9ef866a3d3879220f'), ObjectId('699534f9ef866a3d38792210'), ObjectId('699534f9ef866a3d38792211'), ObjectId('699534f9ef866a3d38792212'), ObjectId('699534f9ef866a3d38792213'), ObjectId('699534f9ef866a3d38792214'), ObjectId('699534f9ef866a3d38792215'), ObjectId('699534f9ef866a3d38792216'), ObjectId('699534f9ef866a3d38792217'), ObjectId('699534f9ef866a3d38792218'), ObjectId('699534f9ef866a3d38792219'), ObjectId('699534f9ef866a3d3879221a'), ObjectId('699534f9ef866a3d3879221b'), ObjectId('699534f9ef866a3d3879221c'), ObjectId('699534f9ef866a3d3879221d'), ObjectId('699534f9ef866a3d3879221e'), ObjectId('699534f9ef866a3d3879221f'), ObjectId('699534f9ef866a3d38792220'), ObjectId('699534f9ef866a3d38792221'), ObjectId('699534f9ef866a3d38792222'), ObjectId('699534f9ef866a3d38792223'), ObjectId('699534f9ef866a3d38792224'), ObjectId('699534f9ef866a3d38792225'), ObjectId('699534f9ef866a3d38792226'), ObjectId('699534f9ef866a3d38792227'), ObjectId('699534f9ef866a3d38792228'), ObjectId('699534f9ef866a3d38792229'), ObjectId('699534f9ef866a3d3879222a'), ObjectId('699534f9ef866a3d3879222b'), ObjectId('699534f9ef866a3d3879222c'), ObjectId('699534f9ef866a3d3879222d'), ObjectId('699534f9ef866a3d3879222e'), ObjectId('699534f9ef866a3d3879222f'), ObjectId('699534f9ef866a3d38792230'), ObjectId('699534f9ef866a3d38792231'), ObjectId('699534f9ef866a3d38792232'), ObjectId('699534f9ef866a3d38792233'), ObjectId('699534f9ef866a3d38792234'), ObjectId('699534f9ef866a3d38792235'), ObjectId('699534f9ef866a3d38792236'), ObjectId('699534f9ef866a3d38792237'), ObjectId('699534f9ef866a3d38792238'), ObjectId('699534f9ef866a3d38792239'), ObjectId('699534f9ef866a3d3879223a'), ObjectId('699534f9ef866a3d3879223b'), ObjectId('699534f9ef866a3d3879223c'), ObjectId('699534f9ef866a3d3879223d'), ObjectId('699534f9ef866a3d3879223e'), ObjectId('699534f9ef866a3d3879223f'), ObjectId('699534f9ef866a3d38792240'), ObjectId('699534f9ef866a3d38792241'), ObjectId('699534f9ef866a3d38792242'), ObjectId('699534f9ef866a3d38792243'), ObjectId('699534f9ef866a3d38792244'), ObjectId('699534f9ef866a3d38792245'), ObjectId('699534f9ef866a3d38792246'), ObjectId('699534f9ef866a3d38792247'), ObjectId('699534f9ef866a3d38792248'), ObjectId('699534f9ef866a3d38792249'), ObjectId('699534f9ef866a3d3879224a'), ObjectId('699534f9ef866a3d3879224b'), ObjectId('699534f9ef866a3d3879224c'), ObjectId('699534f9ef866a3d3879224d'), ObjectId('699534f9ef866a3d3879224e'), ObjectId('699534f9ef866a3d3879224f'), ObjectId('699534f9ef866a3d38792250'), ObjectId('699534f9ef866a3d38792251'), ObjectId('699534f9ef866a3d38792252'), ObjectId('699534f9ef866a3d38792253'), ObjectId('699534f9ef866a3d38792254'), ObjectId('699534f9ef866a3d38792255'), ObjectId('699534f9ef866a3d38792256'), ObjectId('699534f9ef866a3d38792257'), ObjectId('699534f9ef866a3d38792258'), ObjectId('699534f9ef866a3d38792259'), ObjectId('699534f9ef866a3d3879225a'), ObjectId('699534f9ef866a3d3879225b'), ObjectId('699534f9ef866a3d3879225c'), ObjectId('699534f9ef866a3d3879225d'), ObjectId('699534f9ef866a3d3879225e'), ObjectId('699534f9ef866a3d3879225f'), ObjectId('699534f9ef866a3d38792260'), ObjectId('699534f9ef866a3d38792261'), ObjectId('699534f9ef866a3d38792262'), ObjectId('699534f9ef866a3d38792263'), ObjectId('699534f9ef866a3d38792264'), ObjectId('699534f9ef866a3d38792265'), ObjectId('699534f9ef866a3d38792266'), ObjectId('699534f9ef866a3d38792267'), ObjectId('699534f9ef866a3d38792268'), ObjectId('699534f9ef866a3d38792269'), ObjectId('699534f9ef866a3d3879226a'), ObjectId('699534f9ef866a3d3879226b'), ObjectId('699534f9ef866a3d3879226c'), ObjectId('699534f9ef866a3d3879226d'), ObjectId('699534f9ef866a3d3879226e'), ObjectId('699534f9ef866a3d3879226f'), ObjectId('699534f9ef866a3d38792270'), ObjectId('699534f9ef866a3d38792271'), ObjectId('699534f9ef866a3d38792272'), ObjectId('699534f9ef866a3d38792273'), ObjectId('699534f9ef866a3d38792274'), ObjectId('699534f9ef866a3d38792275'), ObjectId('699534f9ef866a3d38792276'), ObjectId('699534f9ef866a3d38792277'), ObjectId('699534f9ef866a3d38792278'), ObjectId('699534f9ef866a3d38792279'), ObjectId('699534f9ef866a3d3879227a'), ObjectId('699534f9ef866a3d3879227b'), ObjectId('699534f9ef866a3d3879227c'), ObjectId('699534f9ef866a3d3879227d'), ObjectId('699534f9ef866a3d3879227e'), ObjectId('699534f9ef866a3d3879227f'), ObjectId('699534f9ef866a3d38792280'), ObjectId('699534f9ef866a3d38792281'), ObjectId('699534f9ef866a3d38792282'), ObjectId('699534f9ef866a3d38792283'), ObjectId('699534f9ef866a3d38792284'), ObjectId('699534f9ef866a3d38792285'), ObjectId('699534f9ef866a3d38792286'), ObjectId('699534f9ef866a3d38792287'), ObjectId('699534f9ef866a3d38792288'), ObjectId('699534f9ef866a3d38792289'), ObjectId('699534f9ef866a3d3879228a'), ObjectId('699534f9ef866a3d3879228b'), ObjectId('699534f9ef866a3d3879228c'), ObjectId('699534f9ef866a3d3879228d'), ObjectId('699534f9ef866a3d3879228e'), ObjectId('699534f9ef866a3d3879228f'), ObjectId('699534f9ef866a3d38792290'), ObjectId('699534f9ef866a3d38792291'), ObjectId('699534f9ef866a3d38792292'), ObjectId('699534f9ef866a3d38792293'), ObjectId('699534f9ef866a3d38792294'), ObjectId('699534f9ef866a3d38792295'), ObjectId('699534f9ef866a3d38792296'), ObjectId('699534f9ef866a3d38792297'), ObjectId('699534f9ef866a3d38792298'), ObjectId('699534f9ef866a3d38792299'), ObjectId('699534f9ef866a3d3879229a'), ObjectId('699534f9ef866a3d3879229b'), ObjectId('699534f9ef866a3d3879229c'), ObjectId('699534f9ef866a3d3879229d'), ObjectId('699534f9ef866a3d3879229e'), ObjectId('699534f9ef866a3d3879229f'), ObjectId('699534f9ef866a3d387922a0'), ObjectId('699534f9ef866a3d387922a1'), ObjectId('699534f9ef866a3d387922a2'), ObjectId('699534f9ef866a3d387922a3'), ObjectId('699534f9ef866a3d387922a4'), ObjectId('699534f9ef866a3d387922a5'), ObjectId('699534f9ef866a3d387922a6'), ObjectId('699534f9ef866a3d387922a7'), ObjectId('699534f9ef866a3d387922a8'), ObjectId('699534f9ef866a3d387922a9'), ObjectId('699534f9ef866a3d387922aa'), ObjectId('699534f9ef866a3d387922ab'), ObjectId('699534f9ef866a3d387922ac'), ObjectId('699534f9ef866a3d387922ad'), ObjectId('699534f9ef866a3d387922ae'), ObjectId('699534f9ef866a3d387922af'), ObjectId('699534f9ef866a3d387922b0'), ObjectId('699534f9ef866a3d387922b1'), ObjectId('699534f9ef866a3d387922b2'), ObjectId('699534f9ef866a3d387922b3'), ObjectId('699534f9ef866a3d387922b4'), ObjectId('699534f9ef866a3d387922b5'), ObjectId('699534f9ef866a3d387922b6'), ObjectId('699534f9ef866a3d387922b7'), ObjectId('699534f9ef866a3d387922b8'), ObjectId('699534f9ef866a3d387922b9'), ObjectId('699534f9ef866a3d387922ba'), ObjectId('699534f9ef866a3d387922bb'), ObjectId('699534f9ef866a3d387922bc'), ObjectId('699534f9ef866a3d387922bd'), ObjectId('699534f9ef866a3d387922be'), ObjectId('699534f9ef866a3d387922bf'), ObjectId('699534f9ef866a3d387922c0'), ObjectId('699534f9ef866a3d387922c1'), ObjectId('699534f9ef866a3d387922c2'), ObjectId('699534f9ef866a3d387922c3'), ObjectId('699534f9ef866a3d387922c4'), ObjectId('699534f9ef866a3d387922c5'), ObjectId('699534f9ef866a3d387922c6'), ObjectId('699534f9ef866a3d387922c7'), ObjectId('699534f9ef866a3d387922c8'), ObjectId('699534f9ef866a3d387922c9'), ObjectId('699534f9ef866a3d387922ca'), ObjectId('699534f9ef866a3d387922cb'), ObjectId('699534f9ef866a3d387922cc'), ObjectId('699534f9ef866a3d387922cd'), ObjectId('699534f9ef866a3d387922ce'), ObjectId('699534f9ef866a3d387922cf'), ObjectId('699534f9ef866a3d387922d0'), ObjectId('699534f9ef866a3d387922d1'), ObjectId('699534f9ef866a3d387922d2'), ObjectId('699534f9ef866a3d387922d3'), ObjectId('699534f9ef866a3d387922d4'), ObjectId('699534f9ef866a3d387922d5'), ObjectId('699534f9ef866a3d387922d6'), ObjectId('699534f9ef866a3d387922d7'), ObjectId('699534f9ef866a3d387922d8'), ObjectId('699534f9ef866a3d387922d9'), ObjectId('699534f9ef866a3d387922da'), ObjectId('699534f9ef866a3d387922db'), ObjectId('699534f9ef866a3d387922dc'), ObjectId('699534f9ef866a3d387922dd'), ObjectId('699534f9ef866a3d387922de'), ObjectId('699534f9ef866a3d387922df'), ObjectId('699534f9ef866a3d387922e0'), ObjectId('699534f9ef866a3d387922e1'), ObjectId('699534f9ef866a3d387922e2'), ObjectId('699534f9ef866a3d387922e3'), ObjectId('699534f9ef866a3d387922e4'), ObjectId('699534f9ef866a3d387922e5'), ObjectId('699534f9ef866a3d387922e6'), ObjectId('699534f9ef866a3d387922e7'), ObjectId('699534f9ef866a3d387922e8'), ObjectId('699534f9ef866a3d387922e9'), ObjectId('699534f9ef866a3d387922ea'), ObjectId('699534f9ef866a3d387922eb'), ObjectId('699534f9ef866a3d387922ec'), ObjectId('699534f9ef866a3d387922ed'), ObjectId('699534f9ef866a3d387922ee'), ObjectId('699534f9ef866a3d387922ef'), ObjectId('699534f9ef866a3d387922f0'), ObjectId('699534f9ef866a3d387922f1'), ObjectId('699534f9ef866a3d387922f2'), ObjectId('699534f9ef866a3d387922f3'), ObjectId('699534f9ef866a3d387922f4'), ObjectId('699534f9ef866a3d387922f5'), ObjectId('699534f9ef866a3d387922f6'), ObjectId('699534f9ef866a3d387922f7'), ObjectId('699534f9ef866a3d387922f8'), ObjectId('699534f9ef866a3d387922f9'), ObjectId('699534f9ef866a3d387922fa'), ObjectId('699534f9ef866a3d387922fb'), ObjectId('699534f9ef866a3d387922fc'), ObjectId('699534f9ef866a3d387922fd'), ObjectId('699534f9ef866a3d387922fe'), ObjectId('699534f9ef866a3d387922ff'), ObjectId('699534f9ef866a3d38792300'), ObjectId('699534f9ef866a3d38792301'), ObjectId('699534f9ef866a3d38792302'), ObjectId('699534f9ef866a3d38792303'), ObjectId('699534f9ef866a3d38792304'), ObjectId('699534f9ef866a3d38792305'), ObjectId('699534f9ef866a3d38792306'), ObjectId('699534f9ef866a3d38792307'), ObjectId('699534f9ef866a3d38792308'), ObjectId('699534f9ef866a3d38792309'), ObjectId('699534f9ef866a3d3879230a'), ObjectId('699534f9ef866a3d3879230b'), ObjectId('699534f9ef866a3d3879230c'), ObjectId('699534f9ef866a3d3879230d'), ObjectId('699534f9ef866a3d3879230e'), ObjectId('699534f9ef866a3d3879230f'), ObjectId('699534f9ef866a3d38792310'), ObjectId('699534f9ef866a3d38792311'), ObjectId('699534f9ef866a3d38792312'), ObjectId('699534f9ef866a3d38792313'), ObjectId('699534f9ef866a3d38792314'), ObjectId('699534f9ef866a3d38792315'), ObjectId('699534f9ef866a3d38792316'), ObjectId('699534f9ef866a3d38792317'), ObjectId('699534f9ef866a3d38792318'), ObjectId('699534f9ef866a3d38792319'), ObjectId('699534f9ef866a3d3879231a'), ObjectId('699534f9ef866a3d3879231b'), ObjectId('699534f9ef866a3d3879231c'), ObjectId('699534f9ef866a3d3879231d'), ObjectId('699534f9ef866a3d3879231e'), ObjectId('699534f9ef866a3d3879231f'), ObjectId('699534f9ef866a3d38792320'), ObjectId('699534f9ef866a3d38792321'), ObjectId('699534f9ef866a3d38792322'), ObjectId('699534f9ef866a3d38792323'), ObjectId('699534f9ef866a3d38792324'), ObjectId('699534f9ef866a3d38792325'), ObjectId('699534f9ef866a3d38792326'), ObjectId('699534f9ef866a3d38792327'), ObjectId('699534f9ef866a3d38792328'), ObjectId('699534f9ef866a3d38792329'), ObjectId('699534f9ef866a3d3879232a'), ObjectId('699534f9ef866a3d3879232b'), ObjectId('699534f9ef866a3d3879232c'), ObjectId('699534f9ef866a3d3879232d'), ObjectId('699534f9ef866a3d3879232e'), ObjectId('699534f9ef866a3d3879232f'), ObjectId('699534f9ef866a3d38792330'), ObjectId('699534f9ef866a3d38792331'), ObjectId('699534f9ef866a3d38792332'), ObjectId('699534f9ef866a3d38792333'), ObjectId('699534f9ef866a3d38792334'), ObjectId('699534f9ef866a3d38792335'), ObjectId('699534f9ef866a3d38792336'), ObjectId('699534f9ef866a3d38792337'), ObjectId('699534f9ef866a3d38792338'), ObjectId('699534f9ef866a3d38792339'), ObjectId('699534f9ef866a3d3879233a'), ObjectId('699534f9ef866a3d3879233b'), ObjectId('699534f9ef866a3d3879233c'), ObjectId('699534f9ef866a3d3879233d'), ObjectId('699534f9ef866a3d3879233e'), ObjectId('699534f9ef866a3d3879233f'), ObjectId('699534f9ef866a3d38792340'), ObjectId('699534f9ef866a3d38792341'), ObjectId('699534f9ef866a3d38792342'), ObjectId('699534f9ef866a3d38792343'), ObjectId('699534f9ef866a3d38792344'), ObjectId('699534f9ef866a3d38792345'), ObjectId('699534f9ef866a3d387923

### Cleaned fake news data

In [8]:
df = pd.read_csv('./data/general/cleaned_fakenewsdata.csv')
df.head()

                                                text label
0  """ Study in journal , Nature Communications :...  REAL
1  """ Zelensky told the council that he was ther...  REAL
2  """ Central bankers and bureaucrats are seizin...  REAL
3  """ Last updated on .From the section Swimming...  REAL
4  THE discussion in the Morning Star and elsewhe...  REAL

In [10]:
df.reset_index().to_dict(orient='records')

[{'index': 0,
  'text': '""" Study in journal , Nature Communications : `` The chain of events that connects the pandemic shutdown to the floods @ @ @ @ @ was heating over land due to aerosol reductions but also cooling over the ocean due @ @ @ @ @ gases , which intensified the land/sea temperature difference in the summer , \'\' explained lead @ @ @ @ @ Nanjing University of Information Science and Technology , in China . `` This in turn @ @ @ @ @ over the South China/Philippines sea and intensified the winds bringing moist air to eastern China @ @ @ @ @ . \'\' `` Because emissions were reduced dramatically in early 2020 when the Covid-19 pandemic @ @ @ @ @ immediate and abrupt change in various components of the climate system . \'\' `` Such @ @ @ @ @ system would be very different from changes in response to continuous but gradual policy-driven emissions @ @ @ """',
  'label': 'REAL'},
 {'index': 1,
  'text': '""" Zelensky told the council that he was there on behalf of those who died in Bucha : “ Civilians who died , who were shot and killed in the back of their head after being tortured . Some of them were shot on the streets . Others were thrown into wells , so they died there suffering. ” Ukrainian President Volodymyr Zelensky broadcast images of Russian atrocities from Bucha , Ukraine , to the United Nations Security Council following a morning address on April 5 . Zelensky told the council that he was there on behalf of those who died @ @ @ @ @ @ @ , who were shot and killed in the back of their head after being tortured . Some of them were shot on the streets . Others were thrown into wells , so they died there suffering. ” Russia ’ s ambassador to the United Nations , Vassily Nebenzia , sat and watched Zelensky ’ s address—then simply rejected the evidence wholesale . “ I understand that you were shown corpses and heard testimonials , but you only saw what they showed you , ” he said . There were “ flagrant inconsistencies in @ @ @ @ @ @ @ being promoted by Ukrainian and Western media. ” It was impossible that Russian forces carried out those atrocities , he said . It was Ukrainian “ terrorists ” who had massacred those civilians . Nebenzia ’ s remarks are just the most recent entry in an orchestrated , deliberate , and utterly desperate attempt to recast and reject evidence of atrocities and war crimes committed in Ukraine . The Kremlin has asked the world to ignore reality and substitute fantasy—or , at the very least , accept that reality is up for debate @ @ @ @ @ @ @ employing a sophisticated digital public relations campaign , which mimics the techniques of open-source intelligence and mixes in a healthy dose of conspiratorial thinking . Thus far , Moscow has utterly failed on most fronts . But its information war is one of attrition : Enough lies and disinformation will eventually find purchase . I recently spoke to Marko Suprun , host and producer of StopFake , a Ukrainian anti-disinformation agency . I was in Washington . He was in Kyiv , Ukraine ’ s capital , where air raid sirens had been @ @ @ @ @ @ @ If the Russian campaign in Ukraine is a war of attrition , he told me , “ disinformation is targeted politics of attrition. ” Understanding how Moscow spins these tales—weaponizing misinformation into disinformation and weaving it into elaborate conspiracy theories—is key to guarding against them . The Ukrainians , the account wrote , “ are at war with their own peaceful residents ” and were responsible for the shelling of the city . The Ukrainian media , it went on , will say “ retreating Russians killed civilians. ” In the ensuing hours @ @ @ @ @ @ @ accounts referenced the photos posted by shocked Ukrainians and asked its million followers : “ This is the question : Who ? ” The account bills itself as referring to the historical name of “ New Russia , ” a broad swath of present-day Ukraine , which includes a region stretching from Crimea to the Donbas . Another account , dubbed “ Rybar , ” called the photos and video “ agitprop , ” claiming that the dead had been killed in the shelling and any mass graves were dug by Ukrainian soldiers @ @ @ @ @ @ @ asking “ who ? ” in the days that followed , some insisting that it was neo-Nazis in the Ukrainian ranks who had tied civilians ’ hands behind their backs and executed them in the streets . Aleksandr Kots , a pro-Kremlin war correspondent for the Komsomolskaya Pravda newspaper , mused on his Telegram page that it would be easy for Ukrainian soldiers to accuse villagers of collaborating , torture them “ for his own pleasure , ” and execute them to blame the invaders . A pro-Russian English-language account would later spin @ @ @ @ @ @ @ withdraw voluntarily , [ Armed Forces of Ukraine ] moves , in [ sic ] liquidates anyone they deem pro-Russian and then claim the Russians massacred people before they left , ” it wrote . “ It ’ s fed to the Western MSM [ mainstream media ] who pick it up without questioning anything as usual. ” By Sunday , pro-Kremlin news outlet Readovka had packaged this skepticism into outright allegations : The images from Bucha represented “ a new wave of fakes about Russia ’ s ‘ war crimes , ’ @ @ @ @ @ @ @ Russian social media site VK , Readovka posted a slowed-down video that showed one of the corpses moving their hand : The “ dead come to life , ” Readovka wrote . The claims continued stacking . On Monday , one account posited that the deaths must be recent because there were “ no signs of natural decomposition. ” Others noted that the presence of white armbands on the bodies—a symbol used by the Russian military to denote civilians—means Russian forces would not have opened fire . Another account noted that a lack @ @ @ @ @ @ @ were not , in fact , shot . These claims are both easily disproved and deliberately impossible to address—a mixture of outright lies and unknowable factors . Bellingcat and the New York Times have both shared satellite images and drone footage showing Russian forces shooting civilians and of bodies lying in the streets for days before the town ’ s liberation . Russia would try and reject that evidence , with Nebenzia telling the U.N. Security Council that “ the corpses on the video in no way resemble those that could have been @ @ @ @ @ @ @ four days. ” ( Some Russian disinformation channels would try and refuse that reporting with their own satellite image analysis , largely based on analyzing the direction of shadows . None of it is compelling . ) The idea that the bodies moved or that they were actors is easily disproved : Analysis of the videos , backed up by photographic evidence , clearly show the bodies from multiple angles . Decomposition , on the other hand , is incredibly hard to predict—complicated by cold temperatures in the week before Ukrainian forces recaptured @ @ @ @ @ @ @ some bodies in the early stages of decomposition suggest they had been there for some days . But the most obvious evidence of decomposition would not occur for weeks . There has been one particular claim , first raised by one of these disinformation channels in early April , that Russian forces had left Bucha on March 30 and therefore couldn ’ t have been responsible for the killings . That claim has since been repeated , emphatically , by the Russian foreign ministry . That claim contradicts other parts of the disinformation @ @ @ @ @ @ @ of March 31 , a Russian news outlet reported that Ukrainian forces had recaptured Irpin , Ukraine , but insisted that Vorzel to the west , Hostomel to the east , and Bucha to the north remained in Russian hands . Later that morning , Russian military TV station Zvezda shared a video of five Russian tanks—marked with the telltale V , which has been used to identify Russian forces in the region , largely those that entered the Kyiv area via Belarus—claiming they “ held back enemy actions ” near Hostomel and @ @ @ @ @ @ @ claimed Ukraine liberated the town on March 31—a detail that would later lead the Russian Embassy in Geneva to proclaim “ either he was too blind too [ sic ] see all the reported dead in the streets , or they appeared there much later ” —his video was not posted until April 1 . Around 10 a.m. local time that morning , a member of the Bucha city council , Taras Shapravsky , uploaded a video describing the situation in the city as “ dangerous ” and “ still occupied , ” @ @ @ @ @ @ @ mines could take some time . Kots , for his part , posted to Telegram around 6 p.m. on April 1 : “ We are leaving Kyiv. ” Official Ukrainian channels would not announce the total liberation of the entirety of Bucha , Irpin , and Hostomel until the night of April 2 . In the early afternoon of April 2 , a Telegram channel linked to the Russian quasi-private military contractor Wagner Group posted a video of the airfield at Hostomel . “ The command , unable to fulfill the general strategic @ @ @ @ @ @ @ our soldiers to leave and retreat from the reclaimed territories , including Bucha and Irpin , ” it wrote . “ So everyone has more questions than answers. ” The preponderance of evidence implicating Russian forces was even too much for Michael de la Broc , who runs a self-described “ pro-Russian ” Telegram channel . De la Broc wrote that Russian forces were clearly in control of Bucha at the time the murders took place and that there was no other explanation for the killings . “ You can hide from this @ @ @ @ @ @ @ these are Ukrainian fakes . … But someday , we will have to face the truth : These are OUR relatives , friends , acquaintances , and loved ones. ” Hiding from the information is exactly the point , however . These disinformation channels have not only questioned what really happened in Bucha but have tried to turn it into a culture war . One account wrote that the photos from Bucha were an attempt to “ cancel Russia ” and insisted that it was an attempt to distract from the fact that @ @ @ @ @ @ @ created next to our country , ” which includes Fox News host Tucker Carlson ’ s new favorite canard : “ a network of secret bio-laboratories. ” Open-source intelligence analysts , from the professional work of Bellingcat to armchair researchers , have played a vital role in cataloging every aspect of the Russian invasion . That evidence has helped garner international support for Ukraine and mount pressure on Russia . Someday , the evidence collected by these open-source intelligence researchers—everything from photos and videos to radio chatter , satellite images , and social @ @ @ @ @ @ @ proceedings against the Russians responsible for the war . Moscow , in turn , has tried to use those open-source intelligence tactics or a warped version of them for their own advantage . This constellation of disinformation channels has tried , wherever possible , to sow doubt about the evidence collected by those researchers and journalists . This isn ’ t entirely new : Russia turned its disinformation machine to the 2013 chemical weapons attack in Ghouta , Syria , blaming medic group the White Helmets . It deflected responsibility onto Ukraine for @ @ @ @ @ @ @ the Donbas . It denied that its special forces were involved in fighting in the Donbas and Crimea in 2014 . In each of those cases , Russia and its allies were clearly responsible . In each of those instances , these disinformation channels have tried to hold up photographic and video evidence—alleging that videos of the White Helmets prove their intent to stage the attack or that eyewitness accounts prove that Ukraine shot down Malaysia Airlines Flight 17 , not Russian-backed separatists . Trying too hard to disprove this disinformation eventually hits @ @ @ @ @ @ @ of how invasions work alone , it ’ s not hard to conclude that it was Russian forces who massacred Ukrainian civilians . Claims that the other side is guilty of slaughtering their own people to garner international support go back a long way—many of the Russian disinformation accounts even drew comparisons to the Srebrenica massacre , suggesting , despite overwhelming evidence , that Serbia ’ s killing of thousands of Bosnian men in 1995 was a false flag . In this case , we have photographs , satellite images , drone footage @ @ @ @ @ @ @ chatter from Russian forces . That radio chatter , heard by Der Spiegel , suggests the Wagner Group may have been on the ground in Bucha , as suggested by the cryptic Telegram posts . The group has been accused of brutal war crimes against unarmed civilians in Syria and farther afield . That is apparently not enough for recently reelected Hungarian Prime Minister Viktor Orban , who was criticized by his allies in Poland for refusing to accept that Russia perpetrated the killings . Despite Russia ’ s flimsy defense , some @ @ @ @ @ @ @ . Writer Michael Tracey tweeted to his 240,000 followers that the photos were “ war propaganda ” and cast doubt on their authenticity . Conspiracy site Infowars ran breathless coverage touting information , largely cribbed from those pro-Russian Telegram channels , that “ exposes the truth ” of what happened in Bucha . To cast doubt on Russia ’ s culpability , Infowars turned to de la Broc—who had suddenly ditched his appeal to “ face the truth ” and begun insisting that the photographic evidence was “ obviously staged. ” That ’ @ @ @ @ @ @ @ to such claims . The Russian disinformation operation is just that : an operation . Its assault on the truth is tactical . Switching from a moral position to shameless lying is both necessary and expected . The point isn ’ t to convince the world that these war crimes didn ’ t happen : The objective is to sow just enough doubt to stymie action . Yet Russia escaped with relatively light consequences , considering its flagrant violations of international law . It had good reason to think it could get away @ @ @ @ @ @ @ of Ukraine this February . That ’ s because , each and every time , useful idiots and bad actors in the United States find a way to spin a domestic version of the Russian narrative . In the process , they weaken and bend the clear , unassailable reality : that Russia has enabled the use of chemical weapons and nerve agents , that its rogue operators downed civilian aircraft , and that it invaded a peaceful country . Each time those narratives take root , it raises the political cost of @ @ @ @ @ @ @ be unaffordable . """',
  'label': 'REAL'},
 {'index': 2,